# Generated by Django 5.2 on 2025-04-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['date'], 'verbose_name': 'Представление', 'verbose_name_plural': 'Представления'},
        ),
        migrations.RemoveField(
            model_name='performance',
            name='location',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='performance',
            name='tickets_available',
            field=models.IntegerField(default=0, verbose_name='Доступно билетов'),
        ),
        migrations.AlterField(
            model_name='play',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность (минут)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genre',
            field=models.CharField(choices=[('C', 'Комедия'), ('D', 'Драма'), ('T', 'Трагедия'), ('M', 'Мюзикл')], max_length=1, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='play',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
