# Generated by Django 5.2 on 2025-04-03 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='actors',
            field=models.ManyToManyField(related_name='performances', to='theater.actor'),
        ),
        migrations.AddField(
            model_name='performance',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='performance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='performance',
            name='play',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='theater.play'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='tickets_available',
            field=models.IntegerField(default=100),
        ),
    ]
