# Generated by Django 5.2 on 2025-04-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0004_performance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='play_venues/', verbose_name='Изображение места'),
        ),
        migrations.AlterField(
            model_name='director',
            name='gender',
            field=models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='director',
            name='years_of_experience',
            field=models.IntegerField(verbose_name='Опыт работы (лет)'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genre',
            field=models.CharField(choices=[('drama', 'Драма'), ('comedy', 'Комедия'), ('tragedy', 'Трагедия')], max_length=20, verbose_name='Жанр'),
        ),
    ]
