# Generated by Django 5.2 on 2025-04-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0005_play_venue_image_alter_director_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['title'], 'verbose_name': 'Спектакль', 'verbose_name_plural': 'Спектакли'},
        ),
        migrations.AlterField(
            model_name='play',
            name='genre',
            field=models.CharField(choices=[('drama', 'Драма'), ('comedy', 'Комедия'), ('tragedy', 'Трагедия')], max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='play',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='play_venues/', verbose_name='Изображение площадки'),
        ),
    ]
